# Build settings
gems:
  - jemoji
  - jekyll-paginate

collections:
  projects:

# Site settings
title: "Hengcheng Zhang"
description: > # this means to ignore newlines until "email:"
   My own website

email: Hengcheng.zhang@outlook.com
#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/bike.jpg"

name: 'Hengcheng Zhang'
author: 'Hengcheng Zhang'
author_image: "/assets/images/me.jpg"

permalink:        pretty

# paginate:	5

# url: "http://myblog.***.***" # the base hostname & protocol for your site
# baseurl: "http://www.hengchengzhang.com"
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://www.linkedin.com/in/hengcheng/
    desc: Check me out on LinkedIn

  - icon:	github
    url:	https://github.com/HengchengZhang
    desc:	Follow me on github

  - icon: phone
    url: /assets/cv.pdf
    desc: Contact me via

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
